language: node_js
sudo: required

node_js:
  - "10"

before_install:
  - npm install codecov -g

install:
  - npm ci

before_script:
  - npm run frontend:lint
  - npm run frontend:build
  - npm run frontend:build:prod

script:
  - npm run test:cov

after_success:
  - codecov
