version: 0.2

  pre_build:
    commands:
      - npm ci

  build:
    commands:
      - npm run frontend:lint
      - npm run frontend:build:prod

  post_build:
    commands:
      - npm run test

artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist
