version: 0.2

phases:
  install:
    commands:
      - npm install codecov -g

  pre_build:
    commands:
      - npm ci

  build:
    commands:
      - npm run frontend:lint
      - npm run frontend:build
      - npm run frontend:build:prod

  post_build:
    commands:
      - npm run test:cov
    finally:
      - codecov

artifacts:
  files:
    - '**/*'
  base-directory: frontend/dist
