language: node_js
sudo: required

node_js:
  - "10"

before_install:
  - npm install codecov -g

install:
  - npm ci

before_script:
  - npm run lint
  - npm run build
  - npm run build:prod

script:
  - npm run test:cov
  - npm run cy:serve-and-run

after_success:
  - codecov
