language: node_js
sudo: false
node_js:
  - node
  - 'lts/*'
before_install:
  - npm install codecov -g
before_script:
  - npm run lint
script:
  - npm run test:cov
  - npm run test:e2e
after_success:
  - codecov
