language: node_js
sudo: required

node_js:
  - "10"

before_install:
  - npm install codecov -g
  - sudo apt-get update -y
  - sudo apt-get install apt-transport-https
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:canonical-chromium-builds/stage
  - sudo apt-get update -y
  - sudo apt-get install -y chromium-browser

install:
  - npm ci

before_script:
  - npm run frontend:lint
  - npm run frontend:build
  - npm run frontend:build:prod

script:
  - npm run test:cov

after_success:
  - codecov
