language: node_js
sudo: required

node_js:
  - "10"

before_install:
  - npm install codecov -g
  - sudo apt-get update -y
  - sudo apt-get install apt-transport-https
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:canonical-chromium-builds/stage
  - sudo apt-get update -y
  - sudo apt-get install -y chromium-browser

install:
  - (cd backend; npm ci)
  - (cd frontend; npm ci)

before_script:
  - (cd frontend; npm run lint)
  - (cd backend; npm run build)
  - (cd frontend; npm run build)

script:
  - (cd backend; npm test:cov)
  - (cd frontend; npm test:cov)
  - (cd frontend; npm run build:prod)

after_success:
  - codecov
